config/routes.rb
Rails.application.routes.draw do
  

  root 'pages#home'         # 首頁
  get 'home', 'math', :form, controller: 'pages'
  post :about, controller: :pages
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  	# 當收到 GET /home 或 GET / 會執行
	def home
		# render 'pages/home'
		# render 'home'
		# 省略設定
	end

	# 當收到 GET /about/me 會執行
	def about
		#render 'pages/about'

		# 兩種方式取得 name 變數
		@name = "#{params[:first_name]} #{params[:last_name]}"  # => "大豆"
		#params['name']                                         # => "大豆"

		# render layout: 'admin'                                # 指定版型
		# render 'pages/about', layout: 'admin'                  # 仔細一點可以寫成這樣
	end

	# 如果不放入任何的def網站仍可運作

	# 訪問 GET /math 時會執行
	def math
		@numbers = (1..46).to_a.sample(6)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
	def nav_li text, path
		active = request.path == path ? :active : nil
		content_tag :li, link_to(text, path), class: active
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>後台</title>
	<%= stylesheet_link_tag    'admin' %>
	<!--<%= javascript_include_tag 'admin' %>-->
</head>
<body>
	<h1>後台</h1><hr>
	<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar', line_number: 1 %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>關於本站</h1>
<p>歡迎！<%= @name %></p>

app/views/pages/form.html.erb
<!--<form action="/about" method="post">-->
	<!--<%= token_tag %>-->
<%= form_tag about_path do %>
	<!--<input type="text" name="first_name">
	<input type="text" name="last_name">
	<input type="submit">-->
	<%= text_field_tag :first_name %>
	<%= text_field_tag :last_name %>
	<%= submit_tag %>
<% end %>
<!--</form>-->

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/math.html.erb
<!-- app/views/pages/math.html.erb -->
<!--<h1><%= 1 + 1 %></h1>

<% if rand > 0.5 %>
<h1>好大</h1>
<% else %>
<h1>好小</h1>
<% end %>-->

<ul>
<% @numbers.each do |i| %>
	<li><%= i %></li>
<% end %>
</ul>

app/views/shared/_navbar.html.erb
<ul>
	<!--<li><%= link_to '首頁', root_path %></li>-->
	<%= nav_li '首頁', root_path %>
	<%= nav_li '關於', about_path %>
	<%= nav_li '樂透', math_path %>
	<%= nav_li '表單', form_path %>
</ul>
<% line_number.times do %>
<hr>
<% end %>